Add dtype option to identity_like
aesara-devs/aesara pull request #1018
Opened 2022-06-27 18:31 UTC by guyrt

Resolves GH816 - adds optional dtype parameter to identity_like which makes it more like the existing *_like functions. 

This is a relatively minor improvement that I pulled off the "good first issue" task. New here (but interested in being more involved) so apologies for any annoying formatting fixes needed. 

Note that mypy seemed to trigger one unrelated problem:

    aesara/link/c/cmodule.py:2439: error: Unused "type: ignore" comment

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [ ] There is an informative high-level description of the changes.
+ [ ] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [ ] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [ ] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

2022-06-27 19:06 UTC, ricardoV94 requested changes
Hi and thanks for opening a PR. It looks alright but the tests are a bit too heavy for the changes introduced. It should be enough to test the dtypes are what is expected without compiling and evaluating an Aesara function.

Also you seem to be reverting previous unrelated changes by accident. That has to be fixed.

Let us know if you have any questions.

2022-06-27 22:31 UTC, guyrt commented
I narrowed test scope and resolved comment above. 


>>> Also you seem to be reverting previous unrelated changes by accident. That has to be fixed.
I don't see this in my diff or commit list. Can you clarify what you are seeing? Note that I'll squash prior to merge to clean up the "merged master" commit I just introduced.

2022-06-27 22:42 UTC, guyrt commented on tests/tensor/test_basic.py
> +    res = aesara.function([m], identity_like(m))
I see - was missing the other tests for this.

2022-06-28 06:30 UTC, ricardoV94 commented on tests/tensor/test_basic.py
> +def test_identity_like():
Shall we give it a more specific name?

```suggestion
def test_identity_like_dtype():
```

2022-06-28 06:33 UTC, ricardoV94 commented
> I don't see this in my diff or commit list. Can you clarify what you are seeing? Note that I'll squash prior to merge to clean up the "merged master" commit I just introduced. 

I don't see any changes being reverted anymore, so that's fine.

Do you mind squashing the commits and pushing so there is only one commit in your PR? We usually merge by rebase and not squash so the PR must already be "clean"

2022-06-28 17:04 UTC, ricardoV94 requested changes
I think you need spaces before parameters and return

2022-06-28 17:04 UTC, ricardoV94 commented on aesara/tensor/basic.py
> +    Parameters
```suggestion
    
    Parameters
```

2022-06-28 17:04 UTC, ricardoV94 commented on aesara/tensor/basic.py
> +    Returns
```suggestion
    
    Returns
```

2022-06-28 19:33 UTC, guyrt reviewed
fixed spacing

2022-06-28 19:33 UTC, guyrt commented on aesara/tensor/basic.py
> +    Parameters
fixed

2022-06-28 19:39 UTC, ricardoV94 requested changes
Apologies for the piecemeal review. I think there is an issue with the docs that you changed. Otherwise everything looks alright.

2022-06-28 19:39 UTC, ricardoV94 commented on doc/library/tensor/basic.rst
> +    Returns a tensor the shape of `x` with ones on main diagonal and zeroes everwhere else.
This seems to be repeating the text above and not properly formatted.

2022-06-29 15:06 UTC, guyrt commented
Fixed docs and rebased

2022-06-30 05:21 UTC, merged

2022-06-30 05:22 UTC, ricardoV94 commented
Thanks @guyrt