Add Owens-T Function `Op`
aesara-devs/aesara pull request #1083
Opened 2022-07-29 13:13 UTC by RuneDominik

This draft PR adds `scipy.special's` `owens_t`-function, needed primarily in the computation of a skewed Gaussian's CDF [1]. The gradient is taken from wolfram alpha ([2] and [3]).

As I've never contributed to aesara before I'm open for any feedback. 

[1] https://en.wikipedia.org/wiki/Skew_normal_distribution
[2] https://www.wolframalpha.com/input?i=d%2Fdh+OwenT%5Bh%2C+a%5D
[3] https://www.wolframalpha.com/input?i=d%2Fda+OwenT%5Bh%2C+a%5D

Here are a few important guidelines and requirements to check before your PR can be merged:

- [x] There is an informative high-level description of the changes.
- [x] The description and/or commit message(s) references the relevant GitHub issue(s).
- [x] [pre-commit](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
- [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [x] The commits correspond to [relevant logical changes](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are no commits that fix changes introduced by other commits in the same branch/BR.
- [x] There are tests covering the changes introduced in the PR.

2022-07-29 19:33 UTC, brandonwillard requested changes
Thanks for the contribution!

This new `Op` needs some tests before we can consider merging it.  Take a look at `tests.tensor.test_math_scipy`; from there you can see that a lot of `Op`s like this one can be tested with only a `makeBroadcastTester` and some test input values.

2022-08-01 14:01 UTC, RuneDominik commented
While writing the tests, some errors became apparent (wrong normalization in the gradient and wrong dtype due to the use of `upgrade_to_float64`). Consequently I will have to rewrite the history to meet the PR-requirements. I'll do so when no further substantial requests exist.

2022-08-04 09:38 UTC, RuneDominik commented
Please let me know If I should further change the history of the PR. I'm not 100% sure if my rebasing-outcome is what is intended to be endorsed by the PR Guidlines.

2022-08-04 17:51 UTC, brandonwillard commented
> Please let me know If I should further change the history of the PR. I'm not 100% sure if my rebasing-outcome is what is intended to be endorsed by the PR Guidelines.

It looks like this branch needs to be rebased onto upstream's (i.e. this repo's) `main`, because it appears to have picked up some unrelated commits from there.

2022-08-05 09:18 UTC, RuneDominik commented
Thanks for the hint, should be fixed now.

2022-08-07 08:48 UTC, ricardoV94 approved these changes

2022-08-09 00:30 UTC, brandonwillard approved these changes
These commits need to be squashed before merging; otherwise, there appears to be no Python-mode coverage, but that's fine (due to how simple and direct those implementations are).

2022-08-09 00:30 UTC, brandonwillard commented on aesara/scalar/math.py
> +    """
```suggestion
```
This docstring isn't adding any extra information, so it's not necessary.  Also, I don't believe it's in NumPy format (i.e. it shouldn't start with a newline).

2022-08-10 18:25 UTC, brandonwillard approved these changes

2022-08-11 16:44 UTC, merged