[documentation] Update Scan Gibbs sampling example
aesara-devs/aesara pull request #1189
Opened 2022-09-16 09:06 UTC by LegrandNico

This PR tries to fix #890.

The example is now working with the last version of Aesara.

2022-09-16 09:17 UTC, rlouf commented on doc/library/scan.rst
> +   trng = at.random.utils.RandomStream(1234)
```suggestion
   trng = at.random.RandomStream(1234)
```

2022-09-16 09:18 UTC, rlouf commented on doc/library/scan.rst
> +   trng = at.random.utils.RandomStream(1234)
It's an implicit convention, but we usually use `srng` for `RandomStream`s

2022-09-16 09:19 UTC, rlouf commented on doc/library/scan.rst
> +   import aesara. tensor as at
```suggestion
   import aesara.tensor as at
```

2022-09-16 13:20 UTC, rlouf commented on doc/library/scan.rst
> +   trng = at.random.RandomStream(1234)
```suggestion
   srng = at.random.RandomStream(1234)
```

2022-09-16 13:21 UTC, rlouf commented on doc/library/scan.rst
> +       return trng.binomial(1, vmean, size=vsample.shape)
```suggestion
       return srng.binomial(1, vmean, size=vsample.shape)
```

2022-09-16 13:22 UTC, rlouf commented
Thank you for contributing. I tried to make it run on my machine (with `matrix` and `vector`s instead of shared variables), and the comments are left are the took things that prevented it from running.

2022-09-16 16:06 UTC, brandonwillard requested changes
Just some formatting changes to match the rest of the library.

N.B. We really should find a way to run black on our code snippets in the documentation.

2022-09-16 16:06 UTC, brandonwillard commented on doc/library/scan.rst
> +       vmean = at.sigmoid(at.dot(hsample, W.T) + bvis)
```suggestion
   def one_step(vsample):
       hmean = at.sigmoid(at.dot(vsample, W) + bhid)
       hsample = srng.binomial(1, hmean, size=hmean.shape)
       vmean = at.sigmoid(at.dot(hsample, W.T) + bvis)
```

2022-09-16 16:06 UTC, brandonwillard commented on doc/library/scan.rst
>     values, updates = aesara.scan(OneStep, outputs_info=sample, n_steps=10)
```suggestion
   values, updates = aesara.scan(one_step, outputs_info=sample, n_steps=10)
```

2022-09-16 16:06 UTC, brandonwillard commented on doc/library/scan.rst
> +   bhid_values = np.random.random((2,))
```suggestion
   import numpy as np
   
   rng = np.random.default_rng(203940)
   W_values = rng.normal(size=(2, 2))
   bvis_values = rng.normal(size=(2,))
   bhid_values = rng.normal(size=(2,))
```

2022-09-16 16:09 UTC, rlouf commented
> N.B. We really should find a way to run `black` on our code snippets in the documentation.

And run the examples in the CI! For instance this one is not going to compile because of the use of `shared` variables (which are not necessary).

2022-09-16 21:17 UTC, rlouf commented
Unless I missed something the values of the shared variables were not specified.

2022-09-16 21:44 UTC, brandonwillard commented
> Unless I missed something the values of the shared variables were not specified.

They're defined, I believe, just not in the same code block.

2022-09-17 09:59 UTC, LegrandNico commented
> > Unless I missed something the values of the shared variables were not specified.
> 
> They're defined, I believe, just not in the same code block.

I think this is making the example a bit confusing as the creation of the input variables is hidden from the user, and then the code is commented to mention you should presume the variables already exist. It would probably be easier for the understanding to have everything in the same block.

2022-09-17 10:26 UTC, rlouf commented
> It would probably be easier for the understanding to have everything in the same block.

Indeed I always like to copy/paste examples from the documentation when I start playing with a library. I'm sure I'm not the only one.

2022-09-23 21:56 UTC, merged