Propagate RV name during opts
aesara-devs/aesara pull request #503
Opened 2021-07-01 06:31 UTC by ricardoV94

The custom name of `RV` Ops are lost during rewrites. 

I am not sure if this is something we want to accommodate, so I implemented a "fix" just for the `local_dimshuffle_rv_lift` opt. If this sounds like a good idea I can check whether it is needed also for the other opts and implement it.

2021-07-01 20:51 UTC, brandonwillard commented
> The custom name of `RV` Ops are lost during rewrites.
> 
> I am not sure if this is something we want to accommodate, so I implemented a "fix" just for the `local_dimshuffle_rv_lift` opt. If this sounds like a good idea, I can check whether it is also needed for the other opts and implement it.

That's a tough one, because new terms produced by a rewrite are&mdash;well&mdash;new, so it might not make sense to give them the old variables' names; however, for cases like `local_dimshuffle_rv_lift` the output is related enough to the original un-lifted variable to justify some use of the original name.

2021-08-01 22:41 UTC, brandonwillard requested changes
It might not be unreasonable to provide augmented names (e.g. `*_lifted`), but copying the _exact_ names would be inconsistent.

Also, a test for this functionality is better off as something entirely independent from the main functionality tests, especially since it's not something that needs to be checked as often as it is in this approach.

2021-08-05 05:44 UTC, ricardoV94 commented
> Also, a test for this functionality is better off as something entirely independent from the main functionality tests, especially since it's not something that needs to be checked as often as it is in this approach.

I removed the check from the main tests but I think we don't gain anything from it. Two tests had to be copied.

Also if a new output branch is added to the optimization in the future, the author will have to add a new test for that branch (nothing will happen if they forget to propagate the name).

If it's part of the default tests it will be automatically covered. Also it's not really any substantial overhead, just a string equality check.

2021-09-17 03:15 UTC, brandonwillard requested changes

2021-09-17 03:15 UTC, brandonwillard commented on tests/tensor/random/test_opt.py
> +def test_Dimshuffle_lift_remane(ds_order, lifted, dist_op, dist_params, size, rtol):
```suggestion
def test_Dimshuffle_lift_rename(ds_order, lifted, dist_op, dist_params, size, rtol):
```

2021-11-26 04:04 UTC, brandonwillard requested changes
Only a minor change needs to be dropped; otherwise, looks good.

2021-11-26 04:04 UTC, brandonwillard commented on tests/tensor/random/test_opt.py
> +def test_Dimshuffle_lift(ds_order, lifted, dist_op, dist_params, size, rtol):
```suggestion
def test_DimShuffle_lift(ds_order, lifted, dist_op, dist_params, size, rtol):
```

2021-11-30 17:23 UTC, merged