Enabled type checking as described by PEP 561
aesara-devs/aesara pull request #799
Opened 2022-01-30 13:58 UTC by michaelosthege

[PEP 561](https://www.python.org/dev/peps/pep-0561/) describes how packages can tell tools such as `mypy` that they support typechecking.
Essentially there are three options:
* Separately released "stub packages"
* `.pyi` files with stub definitions
* inline type hints and a `py.typed` file

In Aesara there are already plenty of inline type hints, but it does not yet implement PEP 561.

One can already run `mypy --ignore-missing-import -p aesara`, but running type checks on a higher-level package (e.g. `mypy -p pymc`) does not take the type hints from Aesara into account.

<details><summary>Current mypy results for Aesara.</summary>

```
aesara\configparser.py:28: error: Incompatible types in assignment (expression has type "classmethod[Any]", variable has type "Callable[[AesaraConfigWarning, Any, Any], Any]")
aesara\graph\optdb.py:71: error: Item "GlobalOptimizer" of "Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]]" has no attribute "name"
aesara\graph\optdb.py:71: error: Item "LocalOptimizer" of "Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]]" has no attribute "name"
aesara\graph\optdb.py:74: error: Item "GlobalOptimizer" of "Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]]" has no attribute "name"
aesara\graph\optdb.py:74: error: Item "LocalOptimizer" of "Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]]" has no attribute "name"
aesara\graph\optdb.py:76: error: Item "GlobalOptimizer" of "Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]]" has no attribute "name"
aesara\graph\optdb.py:76: error: Item "LocalOptimizer" of "Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]]" has no attribute "name"
aesara\graph\optdb.py:390: error: Signature of "register" incompatible with supertype "OptimizationDatabase"
aesara\graph\optdb.py:390: note:      Superclass:
aesara\graph\optdb.py:390: note:          def register(self, name: str, optimizer: Union[OptimizationDatabase, Union[GlobalOptimizer, LocalOptimizer]], *tags: str, use_db_name_as_tag: Any = ...) -> Any
aesara\graph\optdb.py:390: note:      Subclass:
aesara\graph\optdb.py:390: note:          def register(self, name: Any, obj: Any, position: Union[str, int, float], *tags: Any, **kwargs: Any) -> Any
aesara\graph\optdb.py:435: error: "GlobalOptimizer" object is not iterable
aesara\graph\optdb.py:435: error: "LocalOptimizer" object is not iterable
aesara\graph\optdb.py:452: error: "SeqOptimizer" has no attribute "name"
aesara\graph\basic.py:659: error: Missing return statement
aesara\graph\basic.py:713: error: Argument 1 to "add" of "set" has incompatible type "Hashable"; expected "T"
aesara\graph\basic.py:718: error: Incompatible types in "yield" (actual type "Tuple[T, Optional[Sequence[T]]]", expected type "T")
aesara\graph\basic.py:955: error: Argument 1 to "setdefault" of "dict" has incompatible type "Apply"; expected "Variable"
aesara\graph\basic.py:1085: error: "list" expects 1 type argument, but 2 given
aesara\graph\basic.py:1086: error: Argument 2 to "walk" has incompatible type "Optional[Callable[[T], Union[OrderedSet, List[T]]]]"; expected "Callable[[T], Optional[Sequence[T]]]"
aesara\graph\basic.py:1086: error: Argument 2 to "walk" has incompatible type "Optional[Callable[[T], Union[OrderedSet, List[T]]]]"; expected "Callable[[Any], Optional[Sequence[Any]]]"
aesara\graph\basic.py:1106: error: Name "node" already defined on line 1092
aesara\graph\basic.py:1352: error: Name "multi" already defined on line 1335
aesara\graph\basic.py:1685: error: Incompatible types in assignment (expression has type "Tuple[Variable]", variable has type "Tuple[]")
aesara\graph\basic.py:1687: error: Incompatible return value type (got "Tuple[]", expected "Tuple[Variable]")
aesara\link\c\interface.py:234: error: Incompatible return value type (got "Union[Tuple[int], Tuple[Any, ...]]", expected "Tuple[int]")
aesara\graph\type.py:136: error: Variable "aesara.graph.type.Type.Variable" is not valid as a type
aesara\graph\type.py:136: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
aesara\graph\type.py:137: error: Variable "aesara.graph.type.Type.Variable" is not valid as a type
aesara\graph\type.py:137: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
aesara\graph\type.py:160: error: Variable "aesara.graph.type.Type.Variable" is not valid as a type
aesara\graph\type.py:160: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
aesara\graph\type.py:170: error: Variable? has no attribute "type"
aesara\graph\type.py:194: error: Variable "aesara.graph.type.Type.Variable" is not valid as a type
aesara\graph\type.py:194: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
aesara\graph\type.py:205: error: Variable "aesara.graph.type.Type.Constant" is not valid as a type
aesara\graph\type.py:205: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
aesara\graph\type.py:222: error: Variable "aesara.graph.type.Type.Variable" is not valid as a type
aesara\graph\type.py:222: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
aesara\graph\fg.py:126: error: Value of type "Optional[Dict[Variable, Variable]]" is not indexable
aesara\graph\fg.py:127: error: Value of type "Optional[Dict[Variable, Variable]]" is not indexable
aesara\graph\fg.py:130: error: Need type annotation for "execute_callbacks_times" (hint: "execute_callbacks_times: Dict[<type>, <type>] = ...")
aesara\graph\fg.py:135: error: Need type annotation for "_features" (hint: "_features: List[<type>] = ...")
aesara\graph\fg.py:139: error: Need type annotation for "apply_nodes" (hint: "apply_nodes: Set[<type>] = ...")
aesara\graph\fg.py:144: error: Need type annotation for "variables" (hint: "variables: Set[<type>] = ...")
aesara\graph\fg.py:146: error: Need type annotation for "inputs" (hint: "inputs: List[<type>] = ...")
aesara\graph\fg.py:148: error: Need type annotation for "clients" (hint: "clients: Dict[<type>, <type>] = ...")
aesara\graph\fg.py:230: error: Incompatible types in assignment (expression has type "None", variable has type "List[Any]")
aesara\graph\fg.py:231: error: Incompatible types in assignment (expression has type "None", variable has type "List[Variable]")
aesara\graph\fg.py:381: error: Argument 1 to "io_toposort" has incompatible type "Set[Any]"; expected "List[Variable]"
aesara\graph\fg.py:467: error: Item "str" of "Union[Apply, str]" has no attribute "inputs"
aesara\graph\fg.py:473: error: Item "str" of "Union[Apply, str]" has no attribute "inputs"
aesara\graph\fg.py:479: error: Argument 2 to "add_client" of "FunctionGraph" has incompatible type "Tuple[Union[Apply, str], int]"; expected "Tuple[Apply, int]"
aesara\graph\fg.py:480: error: Argument 2 to "remove_client" of "FunctionGraph" has incompatible type "Tuple[Union[Apply, str], int]"; expected "Tuple[Apply, int]"
aesara\graph\fg.py:620: error: Incompatible types in assignment (expression has type "float", variable has type "int")
aesara\graph\fg.py:705: error: Need type annotation for "ords"
aesara\graph\fg.py:731: error: Incompatible types in assignment (expression has type "Set[Variable]", variable has type "Set[Apply]")
aesara\graph\fg.py:766: error: Value of type "Union[FunctionGraph, Dict[Variable, Variable]]" is not indexable
aesara\graph\fg.py:766: error: Incompatible return value type (got "Union[Any, Variable]", expected "FunctionGraph")
aesara\graph\fg.py:766: error: Invalid index type "int" for "Union[FunctionGraph, Dict[Variable, Variable]]"; expected type "Variable"
aesara\graph\fg.py:802: error: Incompatible return value type (got "Tuple[FunctionGraph, Any]", expected "Union[FunctionGraph, Dict[Variable, Variable]]")
aesara\tensor\type.py:20: error: Cannot determine type of "complex_types"
aesara\tensor\type.py:21: error: Ca [...]

2022-01-30 23:40 UTC, brandonwillard requested changes
Since we must first address the issues with the existing type hints&mdash;and maintain some form of quality going forward&mdash;I've created a separate issue that will need to be closed before something like this can be merged: https://github.com/aesara-devs/aesara/issues/800.

2022-02-01 21:00 UTC, michaelosthege commented
In the coming days I'll do a PR that adds a sensible `mypy` config (part of #800).
In that PR I'll also try to fix mypy errors on public API functions where I can, because those are relevant from the outside.

Nevertheless, the PEP doesn't require type hints to be perfect before a package can enable itself for typecheckers.
After a first pass over the public API warnings it would be really valuable for typechecking PyMC if Aesara adopted PEP 651 like ArviZ just did.
Please let me know if you'd be on board with adopting PEP 651 after fixing public API errors (so before the point of running mypy in the pre-commit), because otherwise I will look at other options to get the typechecking working from the outside.

2022-02-01 22:34 UTC, brandonwillard commented
> In the coming days I'll do a PR that adds a sensible `mypy` config (part of #800). In that PR I'll also try to fix mypy errors on public API functions where I can, because those are relevant from the outside.

Sounds good, thanks.


> Nevertheless, the PEP doesn't require type hints to be perfect before a package can enable itself for typecheckers. After a first pass over the public API warnings it would be really valuable for typechecking PyMC if Aesara adopted PEP 651 like ArviZ just did. Please let me know if you'd be on board with adopting PEP 651 after fixing public API errors (so before the point of running mypy in the pre-commit), because otherwise I will look at other options to get the typechecking working from the outside.

We just don't want to release type information that will necessarily confuse, mislead, or break any code that uses it.  Aside from that, we definitely want to do this.

2022-04-14 20:17 UTC, brandonwillard approved these changes

2022-04-14 20:19 UTC, merged