Fix `DiffOp` output type when input has partially known shape
aesara-devs/aesara pull request #855
Opened 2022-03-11 11:50 UTC by ricardoV94

Closes #823

2022-03-11 12:10 UTC, ricardoV94 commented on tests/tensor/test_extra_ops.py
> +            utt.verify_grad(DiffOp(n=11), [a], eps=7e-3)
Fixing this would require changing the gradient logic or adding a bunch of `ifelse` in the gradient expression. Not sure if worth it

2022-03-11 12:17 UTC, ricardoV94 commented
I wonder if we should just remove the `DiffOp` altogether.

Since it doesn't even have a `C` implementation, indexing seems to be actually faster, even for large `n`

2022-03-11 19:23 UTC, brandonwillard requested changes
Looks good; just a minor test setup change required.

2022-03-13 23:59 UTC, brandonwillard commented
> I wonder if we should just remove the `Diff` `Op` altogether.

Yes, it looks like it should be removed.

2022-03-14 00:00 UTC, brandonwillard approved these changes

2022-03-14 06:18 UTC, merged

2022-03-14 06:19 UTC, ricardoV94 commented
> > I wonder if we should just remove the `Diff` `Op` altogether.
> 
> Yes, it looks like it should be removed.

Only for reason I see is that the graph gets large if n is big, but I don't think that's commonly used