Patch ldflags and libs in GCC_compile under windows
aesara-devs/aesara pull request #947
Opened 2022-05-05 13:44 UTC by lucianopaz

Closes #944

On windows systems, the dll or lib libraries don't follow gcc's library naming convention, which means that their file name doesn't have the lib prefix (e.g. libmkl_core.dll). For this reason, gcc's library search fails to find these dynamic link libraries or static libs. An undesired consequence was that aesara (and old theano) was not able to set the correct blas__ldflags to link with mkl, even if the library had been correctly installed.

This PR introduces two GCC_compiler static methods that patch the libs or ldflags that are used during compilation. The static methods specifically target dll and lib files. They search for the library files in the provided library directories, and if a dll or lib is found, the ldflag is set to the absolute path that points to the dll or lib file. As a sidenote, dlls are preferred over libs.

As a consequence, the normal unix-like ldflags will be patched to work in windows as they do in unix. Thanks to this, aesara is now able to set the correct ldflags in windows to link to mkl installations.

2022-05-05 14:59 UTC, lucianopaz commented
Does anyone know how to fix the unreachable code error from mypy? That code only runs on windows, and mypy doesn’t complain when I run it on windows.

2022-05-05 19:09 UTC, lucianopaz commented
It looks like mypy is failing because of [this bug](https://github.com/python/mypy/issues/12545)

2022-05-05 20:12 UTC, brandonwillard commented
> It looks like mypy is failing because of [this bug](https://github.com/python/mypy/issues/12545)

It looks more like this one: https://github.com/python/mypy/issues/5678.

2022-05-06 13:37 UTC, lucianopaz commented
The failing test (`tests/sparse/sandbox/test_sp.py::TestSP::test_maxpool`) passes locally. Maybe the test is flaky?

2022-05-06 21:05 UTC, brandonwillard commented
> The failing test (`tests/sparse/sandbox/test_sp.py::TestSP::test_maxpool`) passes locally. Maybe the test is flaky?

Yeah, that looks like a bad, unseeded test.

2022-05-06 22:27 UTC, brandonwillard requested changes

2022-05-06 22:27 UTC, brandonwillard commented on aesara/link/c/cmodule.py
> +                    lib_dir = lib_dir[1:-1]
Looks like we need coverage for this scenario.  Also, isn't this equivalent to `lib_dir = lib_dir.strip('"')`?  If it is, then you can execute that statement unconditionally.

2022-05-07 02:06 UTC, hectormz commented
Looking forward to this PR! Was just scratching my head about this on Windows. Thanks @lucianopaz

2022-05-07 14:28 UTC, lucianopaz commented
Codecov seems to be linking the old commit instead of the [new one](https://codecov.io/github/aesara-devs/aesara/commit/0dc06efe59cf0455a5b9a5f7d14e587e3cde714e)

2022-05-07 16:20 UTC, merged